PYTHON := python3
VENV := .venv
PIP := $(VENV)/bin/pip

.PHONY: setup lint test demo run

setup:
	$(PYTHON) -m venv $(VENV)
	$(PIP) install --upgrade pip
	$(PIP) install -e .[dev]

lint:
	$(VENV)/bin/ruff check src tests
	$(VENV)/bin/black --check src tests

test:
	$(VENV)/bin/pytest

run demo:
	$(VENV)/bin/python -m {{ name.replace('-', '_') }}
